//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public string UserIdentity { get; set; }
        public string ContestLogInfo1 { get; set; }
        public string ContestLogInfo2 { get; set; }
        public string ContestLogInfo3 { get; set; }
        public string QSOLogFilter { get; set; }
        public string ContestViewFilter { get; set; }
    }
}
